### ISSUE TITLE
ESXIdentity Menu On Spawn, No Matter What

### ISSUE THREAD

**Issue by Leah-UK** [esx-framework/esx_identity#113]
Hello, I'm trying to get Kashacters enabled on my server. However, while using the newest version of esx_identity and with Steam verification enabled it opens the "ESXIdentity Character Registration" menu on spawn, every time which disallows me to use Kash. How can I fix this? I've tried reverting the version and while that does fix this specific issue it creates other issues.

**Comment by Leah-UK** [comment]
I've managed to fix this by using an older version - however, once someone rejoins the server they spawn in as Michael and not their custom character :(

**Comment by FBFezz** [comment]
Kashacters doenst work with new version of esx (that might be why you got the error with new version as well)

**Comment by Leah-UK** [comment]
Huh? With v1-Final?

**Comment by FBFezz** [comment]
Think so, Yeah but might be wrong ik it uses some old code from before the new esx things happened

**Comment by Leah-UK** [comment]
I just tried setting everything up without using Kashacters, and using the newest version on everything. Still broken, spawning in as a random NPC.

**Comment by FBFezz** [comment]
Hmm weird, works for me

**Comment by Leah-UK** [comment]
I wonder what it could be then? Could it be because we're using steam identification? - It sets me back to the right spot etc, it just doesnt give the clothes / custom character back.

**Comment by FBFezz** [comment]
Hmm weird cause im using steam for everything

**Comment by Leah-UK** [comment]
Ugh idk then :(
