### ISSUE TITLE
script error: @esx_identity/server/main.lua:223: atempt to call a nil value (global 'checkNameFormat')

### ISSUE THREAD

**Issue by gdsasa** [esx-framework/esx_identity#125]
Hi have the following error with esx_identity: script error: @esx_identity/server/main.lua:223: atempt to call a nil value (global 'checkNameFormat')

**Comment by emtiazzahid** [comment]
The same happened to me, did you find any solution for that?

**Comment by gdsasa** [comment]
> The same happened to me, did you find any solution for that?

Yes, contact me on discord: Geas#6539

**Comment by branislav94** [comment]
I have the same problem, what is the solution?

**Comment by legend-gta** [comment]
please help me dude

> The same happened to me, did you find any solution for that?



> > The same happened to me, did you find any solution for that?
> 
> Yes, contact me on discord: Geas#6539

i message u name is legend

**Comment by Remaningforce** [comment]
need help with this problem can u help me?
