### ISSUE TITLE
esx_identity not working

### ISSUE THREAD

**Issue by LikeManTV** [esx-framework/esx_identity#86]
Hello,
I have a problem with esx_identity.
It worked before, but now its not working. The UI doesn't show up, so new players can't register and also the /register command isn't working.

I get this error after starting the server (script):

Error loading script server/main.lua in resource esx_identity: @esx_identity/server/main.lua:159: attempt to call a nil value (field 'RegisterCommand')
stack traceback:
@esx_identity/server/main.lua:159: in main chunk
Failed to load script server/main.lua.

Regards,
LikeManTV

**Comment by twigmasters** [comment]
I am having the same error in the server console, I am still working on setting up my server so not sure if new players will have an issue. I just wanted to let you know you are not alone.

**Comment by wulfieh** [comment]
Hey, its happening to me aswell, you guys able to get a fix?

**Comment by twigmasters** [comment]
I am still having the error but not sure its causing an issue, I will have to try making a new character to test it but last time I tried it seemed to work fine.

**Comment by hoff1k** [comment]
I don't see the UI either, any fix?

**Comment by fredwoot** [comment]
Same here...I guess no one knows the solution or want to share it if they know.

**Comment by Fanto66** [comment]
Same, any fix?

**Comment by LikeManTV** [comment]
Hello,
sorry for not answering.
I don't really now how I solved this problem.
I installed new version of esx_identity and maybe the es_extended too.
(Or completly the entire server).
